service: devtube-proxy

provider:
  name: google
  runtime: nodejs
  project: dev-tube
  credentials: service_key.json
  memorySize: 512
  timeout: 540s
  labels:
    application: DevTube Proxy

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

package:
  individually: true
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - yarn*
    - service_key.json
    - data/*.json
  include:
    - ../dist/**
    - ../sitemap.xml
    - "*.js"

functions:
  proxy:
    handler: proxy
    events:
      - http: path
  proxy2:
    handler: proxy
    package:
      include:
        - data/*.json
    events:
      - http: path
