service: devtube-proxy-with-data

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 2048
  timeout: 30s

package:
  exclude:
    - "node_modules/**"
    - ".gitignore"
    - "yarn*"
    - "service_key.json"
  include:
    - "data/*.json"
    - "../dist/**"
    - "../sitemap.xml"
    - "*.js"

functions:
  proxy2:
    handler: handler.proxy2
    events:
      - http: GET proxy2
