
service: devtube-proxy-${env:DEPLOYMENT}

provider:
  name: google
  runtime: nodejs
  project: dev-tube
  credentials: service_key.json
  memorySize: 2048
  timeout: 30s

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - "node_modules/**"
    - ".gitignore"
    - "yarn*"
    - "service_key.json"
    - "src/**"
    - "*.yml"
    - "*.enc"
    - "*.ts"
  include:
    - "./dist/**"
    - "../dist/**"
    - "firebase.json"
    - "data/*.json"

functions:
  - ${file(functions-${env:DEPLOYMENT}.yml)}
