service: devtube-proxy-with-data

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 2048
  timeout: 30

package:
  exclude:
    - ".gitignore"
    - "yarn*"
    - "service_key.json*"
    - "*.ts"
    - "*.json"
  include:
    - "data/*.json"
    - "../dist/**"
    - "*.js"

functions:
  proxy3:
    handler: index.proxy3
    events:
      - http: 
          path: /proxy3
          method: get
      - http: 
          path: /proxy3/{path+}
          method: get
      - http: 
          path: /proxy3/{path+}
          method: post
          
