service: devtube-proxy

provider:
  name: google
  runtime: nodejs
  project: dev-tube
  credentials: service_key.json
  memorySize: 512
  timeout: 540s
  labels:
    application: DevTube

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

package:
  exclude:
    - "node_modules/**"
    - ".gitignore"
    - "yarn*"
    - "service_key.json"
    - "data/*.json"
  include:
    - "../dist/**"
    - "../sitemap.xml"
    - "*.js"

functions:
  proxy:
    handler: proxy
    events:
      - http: path
