language: node_js
branches:
  only:
  - master
before_script:
- git config --global user.email "travis@dev.tube"
- git config --global user.name "Travis at Dev.Tube"
script:
- npm run build

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  repo: watch-devtube/watch-devtube.github.io
  target-branch: master
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master